AY2425S1-CS2103T-T16-4/tp

docs/AboutUs.md
docs/team/ansel-ch.md

Updated Ansel's information in the AboutUs doc. Do let me know if any changes I needed. Thanks.

Add Ansel's AboutUs info

---

docs/DeveloperGuide.md

Update Non-Functional Requirements

Add NFRs to DeveloperGuide.md

---

docs/DeveloperGuide.md

Update Glossary in DeveloperGuide.md

---

src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java

Added the UI Text Layout when user inputs incorrect formats for the MarkAttendanceCommand - Forgot to create it when developing the MarkAttendanceCommand itself.

Add proper Message Usage format for MarkAttendanceCommand

---

src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/assignment/AssignmentQuery.java
src/main/java/seedu/address/model/student/Student.java
src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
src/test/java/seedu/address/logic/parser/AddAssignmentCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/assignment/AssignmentQueryTest.java
src/test/java/seedu/address/model/assignment/AssignmentTest.java
src/test/java/seedu/address/model/student/StudentTest.java
src/test/java/seedu/address/testutil/TypicalAssignments.java

Implement delete assignment

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java

Update list command

---

src/main/java/seedu/address/logic/commands/ViewStudentCommand.java
src/main/java/seedu/address/logic/parser/ViewStudentCommandParser.java

Update references to ViewCommand

---

src/main/java/seedu/address/model/assignment/Grade.java

Closes #102 
Assignment's Grade's regex did not accept 100.0, 100.00.., etc which caused bugs when loading 100.0 from storage back into assignments. 
Added small change to regex to allow for this

Fix Grade Regex Bug with Storage 

---

src/main/java/seedu/address/logic/commands/MarkPresentAllCommand.java
src/main/java/seedu/address/logic/commands/UnmarkPresentAllCommand.java
src/test/java/seedu/address/logic/commands/MarkPresentAllCommandTest.java
src/test/java/seedu/address/logic/commands/UnmarkPresentAllCommandTest.java

Update formatting for date in Mark/UnmarkPresentAllCommand

---

docs/diagrams/DeleteSequenceDiagram.puml

Start updating UML sequence diagram

---

docs/diagrams/DeleteSequenceDiagram.puml

Fix changes to sequence diagram

---

docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Update model uml

---

src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java

Realised there's a major bug in the deleteStudentCommand when you use the student number delete. Do help push this asap.

Fix bug in undo deleteStudent

---

src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
src/main/java/seedu/address/logic/commands/EditAssignmentCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
src/main/java/seedu/address/logic/parser/EditAssignmentCommandParser.java
src/main/java/seedu/address/model/assignment/Assignment.java
src/main/java/seedu/address/model/assignment/AssignmentQuery.java
src/main/java/seedu/address/model/student/Student.java
src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
src/test/java/seedu/address/logic/commands/EditAssignmentCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditAssignmentCommandParserTest.java
src/test/java/seedu/address/model/assignment/AssignmentTest.java
src/test/java/seedu/address/model/student/StudentTest.java
src/test/java/seedu/address/testutil/AssignmentBuilder.java

Add edit assignment

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/CommandHistory.java
src/main/java/seedu/address/logic/commands/CommandStack.java
src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/ui/CommandBox.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandHistoryTest.java
src/test/java/seedu/address/logic/commands/CommandStackTest.java
src/test/java/seedu/address/logic/commands/UndoCommandTest.java

* Closes #141 
Do lmk what other CLI controls you think would make our application more user-friendly.

Basic cli controls

---

src/main/java/seedu/address/logic/commands/DeleteAttendanceAllCommand.java
src/main/java/seedu/address/logic/commands/DeleteAttendanceCommand.java
src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
src/main/java/seedu/address/logic/commands/MarkPresentAllCommand.java
src/main/java/seedu/address/logic/commands/UnmarkPresentAllCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteAttendanceAllCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteAttendanceCommandParser.java
src/main/java/seedu/address/model/student/Student.java
src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java

* Closes #156 
`deleteat n/[Name] d/[Date]` removes attendance record for a student on that date
`deleteatall tg/[Tut_Grp] d/[Date]` removes attendance record for all students within a TG on that date
`undo` implemented as well 
Tests will only be implemented after v1.5

Add DeleteAttendance & DeleteAttendanceAll

---

docs/UserGuide.md

Add attendance commands to UG

---

src/main/java/seedu/address/ui/HelpWindow.java

Update help command link

---

docs/UserGuide.md

Update User Guide with view command

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/ViewStudentCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/student/Student.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java
src/test/java/seedu/address/logic/commands/ViewStudentCommandTest.java

Nathan found a particular bug that had to do with undoing after using a view command, which caused the GUI not to show the unfiltered list thereafter. Hence this implementation fixes all of those bugs.

Update list and view undo

---

src/main/java/seedu/address/model/student/StudentNumber.java

Bug fix student number

---

docs/UserGuide.md
src/main/java/seedu/address/model/assignment/Deadline.java
src/main/java/seedu/address/model/student/StudentNumber.java

Fix Student Number message

---

src/main/java/seedu/address/model/student/TutorialGroup.java

Fix case sensitivity of tutorial group

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

Update parser name to remove additional whitespace

---

docs/UserGuide.md

Standardise the format of optional inputs

---

docs/AboutUs.md
docs/team/gnoossk.md

edit AboutUs

---

src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/ui/MainWindow.java

* Closes #352 
* to be merged after confirmation that this doesn't violate feature freeze

Fix exit command bug with attendancewindows

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/assignment/Deadline.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/MarkAbsentAllCommandTest.java
src/test/java/seedu/address/logic/parser/MarkAbsentAllCommandParserTest.java
src/test/java/seedu/address/logic/parser/MarkPresentAllCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

Widen error message for invalid date inputs to include both formatting issues and nonexistent dates in the correct format.

Fix date bugs

---

docs/images/desktop.ini
src/main/java/seedu/address/logic/commands/AddStudentCommand.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java

Fix deleteall undo

---

docs/DeveloperGuide.md

Update actors in use case

---

docs/DeveloperGuide.md

Update section about opening Jar

---

docs/DeveloperGuide.md

Remove UI details from use case

---

src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/AttendanceWindow.java

Fix FilteredView bug
